version: '3.7'
service:
  movies:
    image: hanvitha/pymovies:v1
    ports:
      - "81:80"
    deploy:
      replicas: 3
  dth:
    image: hanvitha/pydth:v2
    ports:
      - "82:80"
    deploy:
      replicas: 3
  recharge:
    image: hanvitha/pyrecharge:v3
    ports:
      - "83:80"
    deploy:
      replicas: 3
